import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { vi } from 'vitest';
import App from '../src/App';
import { StatusBadge, ProjectOperationCard } from '../src/components/ui';
import { projects } from '../src/fixtures';

vi.mock('@tauri-apps/api/core', () => ({
  invoke: vi.fn((command: string) => Promise.resolve(command === 'hiveai_database_status' ? {
    initialized: true, engine: 'SQLite', schemaVersion: 7, migrationCount: 7, databasePath: 'hiveai.db', foreignKeysEnabled: true, lastMigrationStatus: 'ALREADY_CURRENT', journalMode: 'WAL', busyTimeoutMs: 5000, synchronous: 'NORMAL', integrityStatus: 'ok',
  } : command === 'hiveai_projects_list' ? [{ id: 'registered-1', name: 'Registered Fixture', originalPath: 'C:\\Projects\\Registered Fixture', normalizedPath: 'c:\\projects\\registered fixture', status: 'ACTIVE', priority: 1, preferredBuilder: 'Codex', preferredAuditor: 'GPT Audit', taskSourcePolicy: 'DISCOVER_STANDARD_FILES', registeredAt: '1', lastValidatedAt: '2', repository: { id: 'repo-1', isGitRepository: true, repositoryRoot: 'C:\\Projects\\Registered Fixture', currentBranch: 'main', headSha: 'abc', preferredRemoteUrl: 'https://github.com/example/registered.git', defaultBranch: 'main', githubOwner: 'example', githubRepo: 'registered', remotes: [{ name: 'origin', url: 'https://github.com/example/registered.git' }] } }] : command === 'hiveai_watcher_status' ? { running: true, queueDepth: 0, queueCapacity: 512, projects: [] } : {
    architectureMode: 'RUST_NATIVE_NO_SIDECAR', sidecarEnabled: false, lastError: null,
    legacyCommerceRuntime: { componentId: 'legacy', displayName: 'Legacy AI-Commerce-HQ runtime', kind: 'LEGACY_COMMERCE', state: 'DISABLED', health: 'DISABLED', startedAt: null, lastHeartbeat: null, restartCount: 0, lastError: null, ownership: 'Excluded from H!veAI startup' },
    components: [{ componentId: 'native', displayName: 'H!veAI native core', kind: 'NATIVE_CORE', state: 'HEALTHY', health: 'HEALTHY', startedAt: '1', lastHeartbeat: null, restartCount: 0, lastError: null, ownership: 'H!veAI Rust native core' }, { componentId: 'legacy', displayName: 'Legacy AI-Commerce-HQ runtime', kind: 'LEGACY_COMMERCE', state: 'DISABLED', health: 'DISABLED', startedAt: null, lastHeartbeat: null, restartCount: 0, lastError: null, ownership: 'Excluded from H!veAI startup' }],
  })),
}));

function renderApp(path = '/') { window.history.pushState({}, '', path); return render(<App />); }

describe('H!veAI M02 UI shell', () => {
  it('renders the application shell and command center', () => { renderApp(); expect(screen.getByRole('img', { name: 'H!veAI' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Command Center' })).toBeInTheDocument(); expect(screen.getByText('Project operations')).toBeInTheDocument(); });
  it('exposes sidebar navigation and primary routes', () => { renderApp('/projects'); expect(screen.getByRole('heading', { name: 'Projects' })).toBeInTheDocument(); expect(screen.getByRole('link', { name: 'Projects' })).toHaveClass('nav-active'); });
  it('renders all canonical status badge semantics', () => { render(<StatusBadge state="AUDIT_REQUIRED" />); expect(screen.getByText('Audit required')).toBeInTheDocument(); });
  it('renders a project operation card with progress and actor', () => { render(<ProjectOperationCard project={projects[0]} onAction={() => undefined} />); expect(screen.getByText('Connect project snapshot events')).toBeInTheDocument(); expect(screen.getByText('Codex')).toBeInTheDocument(); });
  it('renders a project cockpit route', () => { renderApp('/projects/formulab'); expect(screen.getByRole('heading', { name: 'FormuLab' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Overview' })).toBeInTheDocument(); });
  it('opens and closes the mock command palette without executing operations', () => { renderApp(); fireEvent.click(screen.getByRole('button', { name: 'Open command palette' })); expect(screen.getByRole('dialog')).toBeInTheDocument(); expect(screen.getByText('Mock navigation only')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Close command palette' })); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); });
  it('keeps the browser Command Center preview neutral and fixture-free', () => { renderApp(); expect(screen.getByText('Preview / Native data unavailable')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: /Scrubbots|placeholder/i })).not.toBeInTheDocument(); });
  it('shows truthful native runtime status and disabled legacy runtime', async () => { Object.defineProperty(window, '__TAURI_INTERNALS__', { configurable: true, value: {} }); renderApp(); await waitFor(() => expect(screen.getByText('RUST NATIVE NO SIDECAR')).toBeInTheDocument()); expect(screen.getAllByText('DISABLED').length).toBeGreaterThan(0); expect(screen.getByText('No sidecar process is configured. Legacy commerce runtime is disabled and excluded from startup.')).toBeInTheDocument(); delete (window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__; });
  it('shows truthful native database readiness', async () => { Object.defineProperty(window, '__TAURI_INTERNALS__', { configurable: true, value: {} }); renderApp(); await waitFor(() => expect(screen.getByText('SQLite schema v7')).toBeInTheDocument()); expect(screen.getByText('7 migrations · hiveai.db · foreign keys enabled')).toBeInTheDocument(); delete (window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__; });
  it('shows registry-scoped filesystem watcher health', async () => { Object.defineProperty(window, '__TAURI_INTERNALS__', { configurable: true, value: {} }); renderApp(); await waitFor(() => expect(screen.getByText('Watching registered roots')).toBeInTheDocument()); expect(screen.getByText('Changes are debounced and refresh evidence locally.')).toBeInTheDocument(); delete (window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__; });
  it('renders persisted project registry records', async () => { Object.defineProperty(window, '__TAURI_INTERNALS__', { configurable: true, value: {} }); renderApp('/projects'); await waitFor(() => expect(screen.getByRole('heading', { name: 'Registered Fixture' })).toBeInTheDocument()); expect(screen.getByText('Git repository')).toBeInTheDocument(); expect(screen.getByText('example/registered')).toBeInTheDocument(); delete (window as Window & { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__; });
});
